from collections.abc import AsyncGenerator
from typing import Any, Protocol


class RedisProtocol(Protocol):
    async def ping(self) -> bool: ...

    async def deduplicate(self, key: str, ttl: int = 86400) -> bool: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def eval(self, script: str, keys: list[str], args: list[str | int]) -> list[int]: ...

    def subscribe(self, channel: str) -> AsyncGenerator[dict[str, Any]]: ...

    async def close(self) -> None: ...
